<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvalaPlugin>true</AvalaPlugin>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Forges\Avala.Forges.Contracts\Avala.Forges.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Avala.Gitea.Tests" />
  </ItemGroup>
</Project>
