<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Avala.Sdk\Avala.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Modules\Agents\Avala.Agents.Contracts\Avala.Agents.Contracts.csproj" />
  </ItemGroup>
</Project>
