<Project>
  <Target Name="AvalaPublishPlugin" AfterTargets="Build" Condition="'$(AvalaPlugin)' == 'true'">
    <ItemGroup>
      <AvalaPluginFile Include="$(OutDir)**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(AvalaPluginFile)"
          DestinationFiles="@(AvalaPluginFile->'$(AvalaRoot)artifacts\plugins\$(AssemblyName)\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
