<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Avala.Sdk\Avala.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Avala.Tasks.UI" />
    <InternalsVisibleTo Include="Avala.Tasks.Tests" />
  </ItemGroup>
</Project>
