<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Avala.Sdk\Avala.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Avala.Storage.Tests" />
  </ItemGroup>
</Project>
