<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Forges\Avala.Forges\Avala.Forges.csproj" />
    <ProjectReference Include="..\Avala.Forges.Testing\Avala.Forges.Testing.csproj" />
    <ProjectReference Include="..\Avala.Testing\Avala.Testing.csproj" />
  </ItemGroup>
</Project>
