<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Workbench\Avala.Workbench\Avala.Workbench.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workbench\Avala.Workbench.UI\Avala.Workbench.UI.csproj" />
    <ProjectReference Include="..\Avala.Testing\Avala.Testing.csproj" />
    <ProjectReference Include="..\Avala.Testing.UI\Avala.Testing.UI.csproj" />
  </ItemGroup>
</Project>
