<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvalaPlugin>true</AvalaPlugin>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Avala.Mermaid\Avala.Mermaid.csproj" />
    <ProjectReference Include="..\..\..\Avala.Sdk.UI\Avala.Sdk.UI.csproj" />
    <ProjectReference Include="..\..\..\Shared\Avala.Components.UI\Avala.Components.UI.csproj" />
  </ItemGroup>
</Project>
