<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Avala.Sdk\Avala.Sdk.csproj" />
    <ProjectReference Include="..\..\Canvas\Avala.Canvas.Contracts\Avala.Canvas.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Avala.Rendering.UI" />
    <InternalsVisibleTo Include="Avala.Rendering.Tests" />
  </ItemGroup>
</Project>
