<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvalaPlugin>true</AvalaPlugin>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Avala.Verification.Contracts\Avala.Verification.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Avala.Verification.Tests" />
  </ItemGroup>
</Project>
